name             'common'
maintainer       'Rudi Starcevic'
maintainer_email 'ooly.me@gmail.com'
license          'All rights reserved'
description      'Installs/Configures common'
long_description 'Installs/Configures common'
version          '0.1.0'

depends 'timezone-ii'
depends 'hostname'
depends 'os-hardening'
depends 'apt-get-periodic'
depends 'unattended_upgrades'
depends 'postfix'
depends 'notify-email-on-boot'
