# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "trusty"

  config.vm.define "sql" do |sql|
    sql.vm.network "private_network", ip: "192.168.33.100"
    sql.ssh.forward_agent = true
    sql.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "sql01.dev.vbx.example.com"
    end
  end

  config.vm.define "app" do |app|
    app.vm.network "private_network", ip: "192.168.33.101"
    app.ssh.forward_agent = true
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "app01.dev.vbx.example.com"
    end
  end

end
