name             'apt-get-periodic'
maintainer       'Rudi Starcevic'
maintainer_email 'ooly.me@gmail.com'
license          'All rights reserved'
description      'Installs/Configures apt-get-periodic'
long_description 'Installs/Configures apt-get-periodic'
version          '0.1.0'
