name             'dnsmasq'
maintainer       'Rudi Starcevic'
maintainer_email 'ooly.me@gmail.com'
license          'All rights reserved'
description      'Installs/Configures dnsmasq'
long_description 'Installs/Configures dnsmasq'
version          '0.1.0'
